### ISSUE TITLE
Needs Images in readme

### ISSUE THREAD

**Issue by dennisivy** [sahil1sk/dennis_hacthon_project#1]
This looks really good, however, I suggest you add some images in the readme so people don't have to start video calls to see all features.

Also, meeting is not working for me but that's ok, just provide images so I can see the concept.

**Comment by sahil1sk** [comment]
Hi Dennis, Many Thanks for the response & recommendation. I updated my readme with images using (Brad Traversy Media   "Mark Down Crash Course").

**Comment by sahil1sk** [comment]
Thanks Again Dennis.
